// generated by stringer -type MoveType; DO NOT EDIT

package engine

import "fmt"

const _MoveType_name = "NoMoveNormalPromotionCastlingEnpassant"

var _MoveType_index = [...]uint8{6, 12, 21, 29, 38}

func (i MoveType) String() string {
	if i >= MoveType(len(_MoveType_index)) {
		return fmt.Sprintf("MoveType(%d)", i)
	}
	hi := _MoveType_index[i]
	lo := uint8(0)
	if i > 0 {
		lo = _MoveType_index[i-1]
	}
	return _MoveType_name[lo:hi]
}
