// generated by stringer -type Piece a.go; DO NOT EDIT

package engine

import "fmt"

const (
	_Piece_name_0 = "NoPiece"
	_Piece_name_1 = "BlackPawnWhitePawnBlackKnightWhiteKnightBlackBishopWhiteBishopBlackRookWhiteRookBlackQueenWhiteQueenBlackKingWhiteKing"
)

var (
	_Piece_index_0 = [...]uint8{0, 7}
	_Piece_index_1 = [...]uint8{0, 9, 18, 29, 40, 51, 62, 71, 80, 90, 100, 109, 118}
)

func (i Piece) String() string {
	switch {
	case i == 0:
		return _Piece_name_0
	case 2 <= i && i <= 13:
		i -= 2
		return _Piece_name_1[_Piece_index_1[i]:_Piece_index_1[i+1]]
	default:
		return fmt.Sprintf("Piece(%d)", i)
	}
}
